image: debian:latest

stages:
  - system tests
  - unit tests # TODO: write some

before_script:
  # setup
  - apt-get update --assume-yes && apt-get upgrade --assume-yes && apt-get install --assume-yes git python3-pip
  # Create alias for /usr/bin/python3 -> /usr/bin/python
  - ln -s /usr/bin/python3 /usr/bin/python
  # upgrade pip
  - python -m pip install --quiet --upgrade pip
  # install requirements
  - python -m pip install -r requirements.txt
  # install test-only requirements
  - python -m pip install coverage pytest
  # install this package (need editable for coverage)
  - python -m pip install --editable .

help_check:
  stage: system tests
  script:
    - . .travis/test-all-bin.sh

import_check:
  stage: system tests
  script:
    - python .travis/test-all-mod.py

test_run:
  stage: system tests
  script:
    - . .travis/test-integrate.sh
    - . .travis/test-posterior.sh
    - . .travis/test-run.sh
