variables:
  BRANCH: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  COMMIT: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  RIFT_IMAGE: $CI_REGISTRY_IMAGE/rift


default:
  image: debian:latest

stages:
  - system tests
  - unit tests # TODO: write some
  - docker image

before_script:
  # setup
  - apt-get update --assume-yes && apt-get upgrade --assume-yes && apt-get install --assume-yes git python3-pip
  # Create alias for /usr/bin/python3 -> /usr/bin/python
  - ln -s /usr/bin/python3 /usr/bin/python
  # upgrade pip
  - python -m pip install --quiet --upgrade pip
  # install requirements
  - python -m pip install -r requirements.txt
  # install test-only requirements
  - python -m pip install coverage pytest
  # install this package (need editable for coverage)
  - python -m pip install --editable .

help_check:
  stage: system tests
  script:
    - . .travis/test-all-bin.sh

import_check:
  stage: system tests
  script:
    - python .travis/test-all-mod.py

test_run:
  stage: system tests
  script:
    - . .travis/test-integrate.sh
    - . .travis/test-posterior.sh
    - . .travis/test-run.sh

build:test:
  image: docker:latest
  stage: docker image
  script:  
   -  docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - suffix=$(echo $CI_COMMIT_BRANCH | cut -d "-" -f 2)
    - docker build --rm --no-cache -t $RIFT_IMAGE:$suffix --file Dockerfile .
    - docker push $RIFT_IMAGE:$suffix
